config/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls', namespace="pages")),
    path('signup',include('pages.urls', namespace="pages")),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from pages import views
app_name='pages'
urlpatterns=[
path('',views.home_page,name='home'),
path('about/',views.about_page,name='about'),
path('login/',views.login_page,name='login'),
path('logout/',views.logout_page,name='logout'),
path("signup/", views.signup_page, name='signup'),
path('catgory/<str:cat>',views.catgory_page,name='catgory'),
path("cart1/",views.cart_page,name="cart1"),
#path("add/",views.carts_add,name="cart_add"),
#path("delete/",views.carts_delete,name="cart_delete"),
#path("update/",views.carts_update,name="cart_update")


] 

pages/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser

from django.urls import reverse



class catgory(models.Model):
    name=models.CharField(max_length=20)    

    def __str__(self):
        return self.name

class customer(models.Model):
    first_name= models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=22)
    email= models.CharField(max_length=220)
    PASSWORD= models.CharField(max_length=220)

    
    def __str__(self):
        return F"{self.first_name} {self.last_name}" 

class merch(models.Model):
    name= models.CharField(max_length=100)
    description = models.CharField(max_length=100, default=True,blank=True,null=True)
    price = models.DecimalField( max_digits=12,default=0, decimal_places=2,)
    catgory=models.ForeignKey(catgory,on_delete=models.CASCADE)

    picrure=models.ImageField(upload_to='upload/product/')
    is_sale=models.BooleanField(default=False)
    sale_price=models.DecimalField( max_digits=12,default=0, decimal_places=2,)
    def __str__(self):
        return self.name


class order(models.Model):
    
    customer=models.ForeignKey(customer,on_delete=models.CASCADE)
    quntity=models.IntegerField(default=1,)
    addres = models.CharField(max_length=400,default="",blank=True)
    phone = models.DecimalField( max_digits=12,default=True, decimal_places=2,)
    release_date = models.DateTimeField(default=datetime.now())
    status= models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

# Create your models here.

pages/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class signup_form(UserCreationForm):
    class Meta:
        model = User
        fields = [ 'username',  'password1', 'password2']
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

        

pages/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import merch,catgory
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import LoginForm
from . import views
from django.views.generic import CreateView
from django.urls import path
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import signup_form
from django.contrib.auth import views as django_auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic

#from webSettings.mixins import SuperuserRequiredMixin

#from .models import User
from .forms import *


def home_page(request):
    all_merch=merch.objects.all()
     
    return render(request,"pages/home.html",{'merch':all_merch})
def about_page(request):
    return render(request,"pages/about.html")
def login_page(request):
     context = {}
     if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now log in')
            return redirect('pages:home')
        else:
            messages.error(request, 'Invalid username or password')
            return redirect('pages:login')
     elif request.method == "GET":
        context['form'] = LoginForm()
     return render(request, 'pages/login.html', context)


@login_required(login_url='pages:login')

def logout_page(request):
    logout(request)
    messages.success(request,"you are now logout")
    return render(request,"pages/home.html")

def signup_page(request):
    if request.method == "POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            User=form.save()
            messages.success(request,"you are new user")
            return render(request,'pages/login.html')
    else:

        form=UserCreationForm()    
    context={'form':form}
    return render(request,'pages/signup.html',context)
def catgory_page(request,cat):
    cat=cat.replace("-"," ")
    try:
        catgory=catgory.objects.get(name=cat)
        merch=merch.objects.filter(catgory=catgory)
        return render(request,'catgory.html',{'merch':merch,'catgory':catgory})
    
    except:
        messages.success(request,("you are now in home"))
        return redirect('pages:home')



        
def cart_page(request):
    return render(request,"pages/cart1.html")
def carts_add(request):
    pass
def carts_delete(request):
    pass
def carts_update(request):
    pass

pages/templates/pages/about.html
{% extends "pages/base.html" %}
{% load static %}
{%block content%}
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">mamad shop</h1>
                <p class="lead fw-normal text-white-50 mb-0">this is the most famous shop in the world </p>
            </div>
        </div>
    </header>

{%endblock%}

pages/templates/pages/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>mamad shop</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body dir="rtl">
        {% include "pages/nav.html" %}
            {%if messages%}
                {%for message in messages%}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">

                     {{message}}
                     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {%endif%}
            {% block content %}

            {% endblock  %}
       
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">mamad love &hearts; your Website 1403</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

pages/templates/pages/cart1.html
{% extends "pages/base.html" %}
{% load static %}
{%block content%}
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">mamad shop</h1>
                <p class="lead fw-normal text-white-50 mb-0">this is the most famous shop in the world </p>
            </div>
        </div>
    </header>

{%endblock%}

pages/templates/pages/create suces.html
{% extends "pages/base.html" %}
{% load static %}
{%block content%}
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">mamad shop</h1>
                <p class="lead fw-normal text-white-50 mb-0">this is the most famous shop in the world </p>
            </div>
        </div>
    </header>
                                                 <h1 class="display-4 fw-bolder">you are new user</h1>

{%endblock%}

pages/templates/pages/home.html
{% extends "pages/base.html" %}
{% load static %}

{%block content%}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">mamad shop</h1>
                    <p class="lead fw-normal text-white-50 mb-0">all kinds of mamad are sold here</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for item in merch %}
                    
                    <div class="col mb-5">
                        <div class="card h-100">
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">ofer Sale</div>

                            <!-- Product image-->
                            <img class="card-img-top" src="{{item.picrure.url}}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ item.name}}</h5>
                                    <!-- Product price-->
                                    
                                    {{item.price}} $mamal
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                     {% endfor %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Special Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$20.00</span>
                                    $18.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Sale Item</h5>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$50.00</span>
                                    $25.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Popular Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    $40.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Sale Item</h5>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$50.00</span>
                                    $25.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fancy Product</h5>
                                    <!-- Product price-->
                                    $120.00 - $280.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Special Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$20.00</span>
                                    $18.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Popular Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    $40.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{%endblock%}

pages/templates/pages/login.html
{% extends "pages/base.html" %}
{% load static %}
{%block content%}
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">enter</h1>
                <p class="lead fw-normal text-white-50 mb-0">login</p>
            </div>
        </div>
    </header>
<form class="form-group"  method="POST",action= ""  >
    {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">username</label>
    <input type="text" class="form-control"name="username",placeholder="enter username">
    
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="password" placeholder="enter password">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
  
  <button type="submit" class="btn btn-secondary">Submit</button>
</form>
{%endblock%}

pages/templates/pages/nav.html
 <!-- Navigation-->
 
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">welcome</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">home</a></li>

                

                <li class="nav-item"><a class="nav-link" href="{%url "pages:about"%}">About</a></li>
                {% if user.is_authenticated  %}
                <li class="nav-item"><a class="nav-link" href="{%url "pages:logout"%}">logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url "pages:signup"%}">signup</a></li>
                <li class="nav-item"><a class="nav-link" href="{%url "pages:login"%}">login</a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{%url "pages:home"%}">All Products</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{%url "pages:catgory" "mamad"%}">mamad Items</a></li>
                        <li><a class="dropdown-item" href="{%url "pages:catgory" "meme"%}">mamad meme</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <a href={%url "pages:cart1"%} class="btn btn-outline-dark" >
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>  
                </a>
             
            </form>
        </div>
    </div>
</nav>

pages/templates/pages/signup.html
{% extends "pages/base.html" %}
{% load static %}
{%block content%}
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">enter</h1>
                <p class="lead fw-normal text-white-50 mb-0">login</p>
            </div>
        </div>
    </header>
    <form action=""method='POST'>
      {{form}}
      {% csrf_token %}

  <button type="submit" class="btn btn-secondary">Submit</button>
    </form>
{%endblock%}